@startuml


class Book {
  -name
  +getName()
}

class BookShelf {
  -last
  -book
  +getBookAt()
  +appendBook()
  +getLength()
  +iterator()
}

class BookShelfIterator{
  - bookShelf
  - index
  +hasNext()
  +next()
}

BookShelf o-> Book
BookShelf <-down-o BookShelfIterator


@enduml
